version: "3.9"
services:
  redpanda:
    image: redpandadata/redpanda:v24.2.7
    command: >
      redpanda start --overprovisioned --smp 1 --memory 512M --mode dev-container
      --kafka-addr PLAINTEXT://0.0.0.0:9092 --advertise-kafka-addr PLAINTEXT://localhost:9092
    ports: ["9092:9092"]

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: pricetracker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  app:
    build: .
    depends_on: [postgres, redpanda]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pricetracker
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
    ports: ["8080:8080"]

volumes:
  pgdata: